### PR TITLE
Check if ProjectName argument is supplied

### LINKED ISSUE #3: activity-translations does not check $1
The script requires that you pass an argument to it and the argument is the name of the project as listed on translate.sugarlabs.org and running the script without an argument will run the script but only remove empty translations without pulling in any translations.

### PR DESCRIPTION
**Pull request by chimosky**
Fixes #3.

@quozl kindly review.

### CODE REVIEW

**Comment by JuiP** [comment]
Tested; works as expected.

**Comment by quozl** [comment]
Thanks.  I've merged e72faba ("Check if ProjectName argument is supplied"), but https://github.com/sugarlabs/sugar-tools/pull/4/commits/d5b406d6d70ac7b386c539287d57fc3255dfbe4d seems odd; what's the purpose of capturing wget output into a variable which is then ignored?

**Comment by chimosky** [comment]
> Thanks. I've merged [e72faba](https://github.com/sugarlabs/sugar-tools/commit/e72faba3a51a403468ca3b845324fed7ddb1cd08) ("Check if ProjectName argument is supplied"), but [d5b406d](https://github.com/sugarlabs/sugar-tools/commit/d5b406d6d70ac7b386c539287d57fc3255dfbe4d) seems odd; what's the purpose of capturing wget output into a variable which is then ignored?

I agree, looking at it now that can be done without that line.

**Comment by chimosky** [comment]
8deef59 fixes it.

@quozl kindly review.

**Comment by quozl** [comment]
Thanks.

Reviewed https://github.com/sugarlabs/sugar-tools/commit/8deef591448f26c18492870591083b22b1430f28.  Yes, this can detect missing directory because there will be an HTTP 404 error response, and wget(1) translates this to 8, per `man wget` section EXIT STATUS.

```log
EXIT STATUS
       Wget may return one of several error codes if it encounters problems.

       0   No problems occurred.
       1   Generic error code.
       2   Parse error---for instance, when parsing command-line options, the
           .wgetrc or .netrc...
       3   File I/O error.
       4   Network failure.
       5   SSL verification failure.
       6   Username/password authentication failure.
       7   Protocol errors.
       8   Server issued an error response.
```

However, all other errors will be re-explained as an incorrect project name, without any correct explanation (due to -q).  Reporting it as incorrect project name when it isn't, is misleading.

If the condition is left as-is, it should just say the translations could not be fetched, and not say anything about the project name, even though in all probability it will likely be the project name at fault.

The condition could be tuned to catch only 8 "Server issued an error response".

If something thinks it is necessary to give an accurate message, then port to Python and use the _requests_ module, or cache a list of project names.

**Comment by JuiP** [comment]
How about if we edit the if condition as - 
`if [ $? -eq 8 ]; then`
Will it do the right thing? @quozl

**Comment by quozl** [comment]
It will be better.  But it won't be right.  For instance with internet disconnected, wget(1) would return non-zero and not 8, and the script would try to continue without reporting a problem.

**Comment by chimosky** [comment]
Closing as PR has moved to #6.

**Pull request closed without merging**
