### PR TITLE
Fix message with correct exit status

### LINKED ISSUE #3: activity-translations does not check $1
The script requires that you pass an argument to it and the argument is the name of the project as listed on translate.sugarlabs.org and running the script without an argument will run the script but only remove empty translations without pulling in any translations.

### PR DESCRIPTION
**Pull request by JuiP**
Reference- #4, Fixes #3 
Tested; Once by entering wrong project name and later by turning off the internet connection.
Please test and review. @chimosky @quozl

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.

* [ ] `wget_output` isn't the output of wget(1), but is the exit status, so perhaps call it `wget_status`,
* [ ] indentation is not consistent,
* [ ] the "\n" is not necessary and will intrude upon the message,
* [ ] the message _Incorrect ProjectName_ is not the only cause of exit status 8, so the message could be misleading.  (it can, for instance, be triggered if you are behind a firewall or proxy that needs authentication before fetching pages),

**Comment by JuiP** [comment]
> the message Incorrect ProjectName is not the only cause of exit status 8, so the message could be misleading. (it can, for instance, be triggered if you are behind a firewall or proxy that needs authentication before fetching pages)

I agree, but is there any other way of ensuring if the message _Incorrect ProjectName_ will be displayed if the argument passed is not the correct project name? I'm not too familiar with script codes, any hints would help. I will find a way to implement.

>  - [ ] wget_output isn't the output of wget(1), but is the exit status, so perhaps call it wget_status,
> - [ ] indentation is not consistent,
>  - [ ] the "\n" is not necessary and will intrude upon the message,

Thanks @quozl , I will fix these once the major issue is tackled.

**Comment by JuiP** [comment]
If there is no specific way to handle such exceptions, maybe I could just change the error message to...

`echo  "Server issued an error response. Checking if ProjectName is one listed on translate.sugarlabs.org might be helpful"`

And I also found this link https://developer.mozilla.org/en-US/docs/Web/HTTP/Status for possible server error responses.

**Comment by quozl** [comment]
Perhaps remove `-q` so the actual response is displayed, and then just say in error that wget failed?

**Comment by JuiP** [comment]
> Perhaps remove -q so the actual response is displayed, and then just say in error that wget failed?

Tried that ! When incorrect project name is passed, it returns this:
`Resolving translate.sugarlabs.org (translate.sugarlabs.org)... failed: Name or service not known.
wget: unable to resolve host address ‘translate.sugarlabs.org’
wget failed
`
I still feel echo what I suggested was better, though removing the -q label helps. It kind of displays the correct message for all exit status other than 0. It's just that in this reference a hint of passing the correct project name might be more useful.
I'll add a commit which I think is better than just wget failed. Please review.

**Comment by JuiP** [comment]
@quozl done in commit `32dba50`
> - [x] wget_output isn't the output of wget(1), but is the exit status, so perhaps call it wget_status,
> - [x] indentation is not consistent,
> - [x] the "\n" is not necessary and will intrude upon the message

**Comment by quozl** [comment]
No such commit.  Be sure to push?

**Comment by quozl** [comment]
Oops, turns out a browser tab left open showed your message but not your commit.  I see it now.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Only one `exit 2` is needed.  The message could be shorter too.  It is a bit verbose.  Remember this is a developer tool, so assume an audience with a clue.

**Comment by JuiP** [comment]
> Thanks. Reviewed. Only one exit 2 is needed. The message could be shorter too. It is a bit verbose. Remember this is a developer tool, so assume an audience with a clue.

Oops, sorry forgot to remove the exit, it had no noticeable effect so seemed to have overlooked that, will be careful next time! Done in `5e06774`

**Comment by chimosky** [comment]
Reopened as #7.

**Pull request closed without merging**
